copyfile: remove callback
iterative/dvc-objects pull request #255
Opened 2023-12-11 04:30 UTC by skshetry

Let's remove the callback in all conditions.

The callbacks are part of fsspec, and they don't support callbacks in localfs either.
I plan on to remove `tqdm` and `TqdmCallback` from `dvc-objects`, which this was blocking.

Let's fix this properly if someone complains. :-)

2023-12-11 12:15 UTC, efiop requested changes
Completely removing feels like a bit too much. We should probably have a bytes-based (+number of objects) progress bar for all files, but that will still need some logic.

> Let's fix this properly if someone complains. :-)

I don't think we can do it this way in this case, this is pretty important. We need some progress indication.

2023-12-11 12:16 UTC, efiop commented
> The callbacks are part of fsspec, and they don't support callbacks in localfs either.

That's not really a feature, it is just missing and needs to be added one way or another.

2023-12-11 12:19 UTC, skshetry commented
> That's not really a feature, it is just missing and needs to be added one way or another.

Either you need to support callback or not. Unfortunately there is no middleground.

2023-12-11 12:22 UTC, efiop commented
> Either you need to support callback or not. Unfortunately there is no middleground.

I'm not sure I understand why it is an unresolvable problem though.

2023-12-11 12:25 UTC, skshetry commented
Looking through the responsibility of an API, if someone passes a `callback` and you decide to not create a callback, you are not honouring your part of promise here.

(Maybe there's a way to skip if we pass `NoopCallback()`)

2023-12-11 12:29 UTC, efiop commented
> Looking through the responsibility of an API, if someone passes a `callback` and you decide to not create a callback, you are not honouring your part of promise here.
> 
> (Maybe there's a way to skip if we pass `NoopCallback()`)

I agree and it probably just shouldn't create a callback on its own at all, but rather use the one provided by the user from a layer above.

2023-12-12 02:27 UTC, skshetry commented
Can be closed, went with #256.

2023-12-12 02:27 UTC, closed without merging